### ISSUE TITLE
How to check field has been filled in before payment, blank field resulting order fail to complete

### ISSUE THREAD

**Issue by nghesi** [brainblocks/woocommerce-brainblocks#12]
hi, I got a small problem on my woocommerce checkout page. I need to check all required filed is submitted before customer is able to click on the Nano payment. Would you please advise how to achieve that. So sorry I am not a professional developer. my website: http://iggmart.com/ if you want to have a look

**Comment by george-viaud** [comment]
Same here - you can reproduce this by not having a valid shipping method for example.

**Comment by nghesi** [comment]
The problem is that after customer complete payment through brainblocks without filling the fields, the site can't register the order.

**Comment by schenkty** [comment]
making every field required will solve this

**Comment by george-viaud** [comment]
Doesn't this still allow the user to pay before completing the form?  A better flow would be to permit the user to pay after the order is submitted but only mark the order as paid once complete.

Of course, I'm speaking only for my particular flow - I'm not sure how this would work for others, though I suspect any flow that allows the user to pay without actually submitting an order is less than optimal and will cause some major customer service issues.

**Comment by schenkty** [comment]
No clue why this would allow the user to pay before completing the form. Every implementation of our plugin that I’ve seen required users to fill out information before payment 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bluepnume** [comment]
FYI, I've uploaded a new version of this plugin, which includes an option (enabled by default) to do a full-page redirect rather than showing the brainblocks button inline. Would appreciate if you can try this instead if you're still seeing problems, as it should resolve some compatibility issues.

https://brainblocks.io/static/woocommerce-gateway-brainblocks.zip

<img width="771" alt="screen shot 2018-03-11 at 2 46 09 pm" src="https://user-images.githubusercontent.com/1219075/37258846-24668280-253b-11e8-987d-957b6d1f87d3.png">

**Comment by nghesi** [comment]
Hi many thanks for your hard work, I am able to make it run for my website using redirecting to brainblocks website. Cheers,
