### ISSUE TITLE
Nano never received in our wallet.

### ISSUE THREAD

**Issue by TristenBlack** [brainblocks/woocommerce-brainblocks#14]
We had a payment recently sent to us that we never got in our wallet. The payment was sent from the customer but we received a notice in woocommerce stating the order failed. It looks like the customer sent it direct from Binance.

Address: | xrb_1339yeo4mnq8byepc6ytf98i7i5a3jb3txuwnk3dnir9a1scobz9b1cds89p
-- | --
Txid: | 8E75736EE9EC413B390D61F8C45FF5D3C62744A6B7C7906BA78C8CEEC96DDA07
Completed

NANO

13.482

2018-05-11 21:42:14
https://raiblocks.net/block/index.php?h=8E75736EE9EC413B390D61F8C45FF5D3C62744A6B7C7906BA78C8CEEC96DDA07

**Comment by schenkty** [comment]
I'm sorry for the extremely late reply - It looks like in this situation,  the customer had paid less than the  requested amount and the funds were refunded back to the sender (in this case Binance). This case can't happen anymore because of an update that we deployed several months back that automatically sends funds from exchanges to the merchant. This prevents the case where exchanges lose track of the funds and in turn, the customer losses their funds. With the change where funds are sent direct to the merchant, the merchant can then communicate with the customer and properly refund the payment. 

I hope this clears up what had happened, I am sorry that we had not replied to this before.
